#!/bin/bash

rm -rf "{{ cookiecutter.project_directory }}"
./bin/fabricate-cookiecutter.py
git diff --exit-code -- "{{ cookiecutter.project_directory }}" > /dev/null
rc=$?
if [[ $rc -eq 1 ]];
then
  git add "{{ cookiecutter.project_directory }}"
  git commit --amend --no-edit
fi;
